version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api-service
    ports:
      - "8111:8111"
    depends_on:
      - server
    networks:
      - app-net

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server-service
    ports:
      - "8112:8112"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
